//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string MaKM { get; set; }
        public string TenKhuyenMai { get; set; }
        public Nullable<double> PTGiam { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<int> SoTienToiThieu { get; set; }
        public string MoTa { get; set; }
    }
}
