//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SanPham
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string MaSP { get; set; }
        [Required] 
        [StringLength(100)] 
        public string TenSP { get; set; }
        [Required]
        public string ChiTiet { get; set; }
        [Required]
        [Range(0, int.MaxValue)] 
        public Nullable<int> GiaBan { get; set; }
        [Required]
        [Range(0, int.MaxValue)] 
        public Nullable<int> SoLuong { get; set; }
        [Required]
        public string HinhAnh { get; set; }
        [Required]
        public string MaDM { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
