//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangThoiTrangHeaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKH
    {
        public string MaLoaiKH { get; set; }
        public string TenLoaiKH { get; set; }
        public Nullable<double> UuDai { get; set; }
        public string ChiTiet { get; set; }
    }
}
